version: '3'
services:
    php-apache:
        build: 
            context: ./docker/php-apache
        ports:
            - 80:80
        volumes:
            - ./api:/var/www/html
        links:
            - 'mariadb'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8000:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
        depends_on:
            - mariadb
            
    mariadb:
        image: mariadb:10.1
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "Europe/Paris"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'toor'
            MYSQL_DATABASE: 'database'

volumes:
    mariadb: